import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { and, desc, eq, sql } from 'drizzle-orm';
import { booking, payment, property, unit } from '@sambung/db';
import type { BookingStatus, PaymentProvider } from '@sambung/shared';
import { TenantContext } from '../common/tenant-context.service';
import { TenantDbService } from '../db/tenant-db.service';

/** Everything the pay path needs about a booking, read under a row lock. The
 * price is nullable in the table (a Block carries none), but a `pending_payment`
 * hold always has one - the service narrows the null after the status check. */
export interface PayContext {
  status: BookingStatus;
  unitId: string;
  totalPriceIdr: bigint | null;
  depositPct: number;
  unitName: string;
  propertyName: string;
  guestName: string | null;
  guestPhone: string | null;
  guestEmail: string | null;
}

/** An open (pending) payment's stored session - what a retry returns unchanged. */
export interface OpenSession {
  provider: PaymentProvider;
  amountIdr: bigint;
  token: string;
  redirectUrl: string;
}

/** The confirmation page's read (api-spec §6.3, #54). Everything `GET
 * /public/bookings/:id` renders, read under the Visitor's RLS scope. Money is
 * bigint (invariant #6) until the service frames it. */
export interface ConfirmationView {
  status: BookingStatus;
  unitId: string;
  checkIn: string;
  checkOut: string;
  propertyName: string;
  unitName: string;
  totalPriceIdr: bigint | null;
  amountPaidIdr: bigint;
  guestName: string | null;
  guestPhone: string | null;
}

/** The row a mint inserts. `id` IS the Provider order id (ADR-0015), generated by
 * the service before the gateway call so a failed call leaves NO row. */
export interface InsertPaymentInput {
  id: string;
  bookingId: string;
  provider: PaymentProvider;
  amountIdr: bigint;
  session: { token: string; redirectUrl: string };
}

/**
 * The payment domain's dumb repository (ADR-0015). Drizzle only, via the
 * tenant-scoped (RLS) client; `payment` has no `tenant_id` of its own, so its RLS
 * policy scopes through the booking join - safe because every method here runs
 * under the Visitor tenant the booking id resolved to.
 */
@Injectable()
export class PaymentsRepository {
  constructor(
    private readonly db: TenantDbService,
    private readonly tenant: TenantContext,
  ) {}

  /**
   * Load the booking's pay context and LOCK its row for the transaction (ADR-0015).
   * The lock serialises concurrent pays on the same booking: a racing second pay
   * waits here, then sees the first's committed payment row and reuses it - so
   * "one payment row per attempt cycle" holds even under a double-submit, without
   * a partial unique index. `FOR UPDATE OF booking` locks only the booking, not
   * the joined unit/property (an owner editing them must not block a guest paying).
   *
   * Only meaningful inside the caller's `db.run` - a lock in its own transaction
   * releases at once. Asserted, because the failure is otherwise silent.
   */
  async lockAndLoad(bookingId: string): Promise<PayContext | null> {
    this.db.assertInTransaction('PaymentsRepository.lockAndLoad');
    const tenantId = this.tenant.tenantId;
    const rows = await this.db.run((tx) =>
      tx
        .select({
          status: booking.status,
          unitId: booking.unitId,
          totalPriceIdr: booking.totalPriceIdr,
          depositPct: property.depositPct,
          unitName: unit.name,
          propertyName: property.name,
          guestName: booking.guestName,
          guestPhone: booking.guestPhone,
          guestEmail: booking.guestEmail,
        })
        .from(booking)
        .innerJoin(
          unit,
          and(eq(unit.id, booking.unitId), eq(unit.tenantId, tenantId)),
        )
        .innerJoin(
          property,
          and(
            eq(property.id, unit.propertyId),
            eq(property.tenantId, tenantId),
          ),
        )
        .where(and(eq(booking.id, bookingId), eq(booking.tenantId, tenantId)))
        .limit(1)
        .for('update', { of: booking }),
    );
    return rows[0] ?? null;
  }

  /** Re-read the booking's status after the opportunistic hold-sweep - the one the
   * payability decision is made on (a lapsed hold has become `expired` by now). */
  async readStatus(bookingId: string): Promise<BookingStatus | null> {
    const tenantId = this.tenant.tenantId;
    const rows = await this.db.run((tx) =>
      tx
        .select({ status: booking.status })
        .from(booking)
        .where(and(eq(booking.id, bookingId), eq(booking.tenantId, tenantId)))
        .limit(1),
    );
    return rows[0]?.status ?? null;
  }

  /**
   * The booking's open (pending) payment session, or null if none exists yet.
   * `raw_payload` holds the Provider session `{ token, redirectUrl }` (ADR-0015);
   * a pending row is only ever written WITH a session (mint happens after the
   * gateway succeeds), so a malformed payload here is corruption - this throws
   * (500) rather than returning null and papering over it with a duplicate mint.
   */
  async findOpenSession(bookingId: string): Promise<OpenSession | null> {
    const rows = await this.db.run((tx) =>
      tx
        .select({
          provider: payment.provider,
          amountIdr: payment.amountIdr,
          rawPayload: payment.rawPayload,
        })
        .from(payment)
        .where(
          and(eq(payment.bookingId, bookingId), eq(payment.status, 'pending')),
        )
        // Newest first: there is normally one, but if a prior mint ever left more
        // than one pending, the latest session is the one to hand back.
        .orderBy(desc(payment.createdAt))
        .limit(1),
    );
    const row = rows[0];
    if (!row) return null;
    const session = row.rawPayload as {
      token?: unknown;
      redirectUrl?: unknown;
    };
    if (
      typeof session?.token !== 'string' ||
      typeof session?.redirectUrl !== 'string'
    ) {
      // A pending row is only ever written WITH a valid session (the mint happens
      // after the gateway succeeds), so a malformed payload here is corruption.
      // Fail LOUD - returning null would send the caller down the mint path and
      // silently create a SECOND pending row (nothing constrains one-per-booking
      // but this lock + reuse), which is worse than a 500 naming the bad row.
      throw new InternalServerErrorException(
        'An open payment has a malformed session payload',
      );
    }
    return {
      provider: row.provider as PaymentProvider,
      amountIdr: row.amountIdr,
      token: session.token,
      redirectUrl: session.redirectUrl,
    };
  }

  /**
   * The booking's status + its unit id (reconcile-on-read, #54). The confirmation
   * service reads this first to decide whether to reconcile (only a
   * `pending_payment` booking has anything to pull) and to sweep the unit's
   * lapsed holds. RLS-scoped, so it 404s a cross-tenant id as "not found".
   */
  async readStatusAndUnit(
    bookingId: string,
  ): Promise<{ status: BookingStatus; unitId: string } | null> {
    const tenantId = this.tenant.tenantId;
    const rows = await this.db.run((tx) =>
      tx
        .select({ status: booking.status, unitId: booking.unitId })
        .from(booking)
        .where(and(eq(booking.id, bookingId), eq(booking.tenantId, tenantId)))
        .limit(1),
    );
    return rows[0] ?? null;
  }

  /** The order id (= `payment.id`) of the booking's open pending payment, or null
   * if the guest never started paying. Reconcile-on-read (#54) hands this to the
   * Provider's status API. Newest-first, matching `findOpenSession`. */
  async findPendingPaymentOrderId(bookingId: string): Promise<string | null> {
    const rows = await this.db.run((tx) =>
      tx
        .select({ id: payment.id })
        .from(payment)
        .where(
          and(eq(payment.bookingId, bookingId), eq(payment.status, 'pending')),
        )
        .orderBy(desc(payment.createdAt))
        .limit(1),
    );
    return rows[0]?.id ?? null;
  }

  /**
   * The confirmation page's view (api-spec §6.3, #54), under the Visitor's RLS
   * scope. `amountPaidIdr` is the sum of SETTLED payments (the Deposit taken
   * online), computed in SQL as exact `bigint` text (never a float, invariant #6)
   * and widened back to BigInt here.
   */
  async readConfirmationView(
    bookingId: string,
  ): Promise<ConfirmationView | null> {
    const tenantId = this.tenant.tenantId;
    const rows = await this.db.run((tx) =>
      tx
        .select({
          status: booking.status,
          unitId: booking.unitId,
          checkIn: booking.checkIn,
          checkOut: booking.checkOut,
          propertyName: property.name,
          unitName: unit.name,
          totalPriceIdr: booking.totalPriceIdr,
          guestName: booking.guestName,
          guestPhone: booking.guestPhone,
          amountPaidIdr: sql<string>`coalesce((
            select sum(${payment.amountIdr})
            from ${payment}
            where ${payment.bookingId} = ${booking.id}
              and ${payment.status} = 'paid'
          ), 0)::text`,
        })
        .from(booking)
        .innerJoin(
          unit,
          and(eq(unit.id, booking.unitId), eq(unit.tenantId, tenantId)),
        )
        .innerJoin(
          property,
          and(
            eq(property.id, unit.propertyId),
            eq(property.tenantId, tenantId),
          ),
        )
        .where(and(eq(booking.id, bookingId), eq(booking.tenantId, tenantId)))
        .limit(1),
    );
    const row = rows[0];
    if (!row) return null;
    return { ...row, amountPaidIdr: BigInt(row.amountPaidIdr) };
  }

  /** Insert the payment row with its session. `id` is the Provider order id, so
   * `provider_ref` mirrors it - the key #53's webhook resolves the booking by. */
  async insertPaymentWithSession(input: InsertPaymentInput): Promise<void> {
    await this.db.run((tx) =>
      tx.insert(payment).values({
        id: input.id,
        bookingId: input.bookingId,
        provider: input.provider,
        providerRef: input.id,
        amountIdr: input.amountIdr,
        status: 'pending',
        rawPayload: input.session,
      }),
    );
  }
}
